name: {{ projectName }}
descrition: {{ description }}

publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: 3.16.3

dependencies:
  animations: 2.0.10
  cupertino_icons: 1.0.6
  equatable: 2.0.5
  firebase_analytics: 10.7.4
  firebase_core: 2.24.2
  firebase_crashlytics: 3.4.8
  firebase_remote_config: 4.3.8
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: 2.3.8
  gap: 3.0.1
  get_it: 7.6.4
  go_router: 12.1.3
  intl: 0.18.1
  json_annotation: 4.8.1
  package_info_plus: 5.0.1
  shared_preferences: 2.2.2
  sheet:
    git:
      url: https://github.com/jamesblasco/modal_bottom_sheet.git
      path: sheet
      ref: d5c9ceb4e2263f63f449ed9b1c212a34c6dcaa5d

dev_dependencies:
  build_runner: 2.4.7
  flutter_launcher_icons: 0.13.1
  flutter_lints: 3.0.1
  json_serializable: 6.7.1

flutter:
  generate: true
  uses-material-design: true
